export const ConfigKeys = {
  API_PORT: 'API_PORT',
  API_PREFIX: 'API_PREFIX',
  APP_ROOT_PATH: 'APP_ROOT_PATH',
  ENCRYPTION_KEY: 'ENCRYPTION_KEY',
  DATABASE_HOST: 'DATABASE_HOST',
  DATABASE_PORT: 'DATABASE_PORT',
  DATABASE_NAME: 'DATABASE_NAME',
  DATABASE_USER: 'DATABASE_USER',
  DATABASE_PASSWORD: 'DATABASE_PASSWORD',
  DATABASE_LOGGING: 'DATABASE_LOGGING',
  DATABASE_AUTOMIGRATE: 'DATABASE_AUTOMIGRATE',
  INITIAL_ADMIN_USERNAME: 'INITIAL_ADMIN_USERNAME',
  LOG_CONSOLE: 'LOG_CONSOLE',
  LOG_DIR: 'LOG_DIR',
  LOG_FILE_MAX_FILES: 'LOG_FILE_MAX_FILES',
  LOG_FILE_MAX_SIZE: 'LOG_FILE_MAX_SIZE',
  LOG_JSON: 'LOG_JSON',
  LOG_LEVEL: 'LOG_LEVEL',
  SESSION_SECRET: 'SESSION_SECRET',
  SESSION_TTL_MS: 'SESSION_TTL_MS',
  ROOT_URI: 'ROOT_URI',
  NODE_ENV: 'NODE_ENV',
  DOCUMENT_STORAGE_ROOT:'DOCUMENT_STORAGE_ROOT', // this only exists in dev
  
  
} as const;

export interface BinderConfig {
  API_PORT?: string;
  API_PREFIX?: string;
  APP_ROOT_PATH: string;
  ENCRYPTION_KEY: string;
  DATABASE_LOGGING?: string;
  LOG_CONSOLE?: string;
  LOG_DIR?: string;
  LOG_FILE_MAX_FILES?: string;
  LOG_FILE_MAX_SIZE?: string;
  LOG_JSON?: string;
  LOG_LEVEL?: string;
  ROOT_URI: string;
  NODE_ENV?: string;
  DATABASE_HOST: string;
  DATABASE_PORT: number;
  DATABASE_NAME: string;
  DATABASE_USER: string;
  DATABASE_PASSWORD: string;
  DATABASE_AUTOMIGRATE?: string;
  INITIAL_ADMIN_USERNAME?: string;
  SESSION_SECRET: string;
  SESSION_TTL_MS?: string;
  DOCUMENT_STORAGE_ROOT?:string;
}
