import { SettingsMapItem, SettingsSection } from './settings';

export const settingsSections: SettingsSection[] = [
  {
    key: 'common',
    label: 'Common Settings',
  },
  {
    key: 'mailer',
    label: 'Email integration',
  },
  {
    key: 'oidc',
    label: 'SSO/OIDC Login',
  },
  {
    key: 'documents',
    label: 'Document storage',
  },
  {
    key: 'pipeline',
    label: 'Processing pipeline',
  },
  {
    key: 'ai',
    label: 'AI assistance',
  },
  {
    key: 'maintenance',
    label: 'Backup and maintenance',
  },
  {
    key: 'security',
    label: 'Security',
  },
  {
    key: 'calendar',
    label: 'Calendar integration',
  },
];

export const settingsMap: SettingsMapItem[] = [
  {
    key: 'mailer.smtp.enabled',
    valueFrom: 'mailer.smtp.enabled',
    encrypted: false,
    default: false,
    label: 'Enable outgoing email',
    type: 'checkbox',
    section: 'mailer',
  },
  {
    key: 'mailer.smtp.host',
    valueFrom: 'mailer.smtp.host',
    encrypted: false,
    default: '',
    label: 'SMTP server host',
    type: 'text',
    section: 'mailer',
  },
  {
    key: 'mailer.smtp.port',
    valueFrom: 'mailer.smtp.port',
    encrypted: false,
    default: '587',
    label: 'SMTP server port',
    type: 'text',
    required: true,
    pattern: '^[1-9][0-9]{0,4}$',
    patternMessage: 'Use the SMTP port number, for example 587 or 465.',
    section: 'mailer',
  },
  {
    key: 'mailer.smtp.secure',
    valueFrom: 'mailer.smtp.secure',
    encrypted: false,
    default: false,
    label: 'Use secure SMTP connection',
    type: 'checkbox',
    section: 'mailer',
  },
  {
    key: 'mailer.smtp.username',
    valueFrom: 'mailer.smtp.username',
    encrypted: false,
    default: '',
    label: 'SMTP username',
    type: 'text',
    section: 'mailer',
  },
  {
    key: 'mailer.smtp.password',
    valueFrom: 'mailer.smtp.password',
    encrypted: true,
    default: '',
    label: 'SMTP password',
    type: 'password',
    section: 'mailer',
  },
  {
    key: 'mailer.smtp.fromAddress',
    valueFrom: 'mailer.smtp.fromAddress',
    encrypted: false,
    default: '',
    label: 'Sender email address',
    type: 'text',
    pattern: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',
    patternMessage: 'Enter a valid email address.',
    section: 'mailer',
  },
  {
    key: 'mailer.smtp.fromName',
    valueFrom: 'mailer.smtp.fromName',
    encrypted: false,
    default: 'Binder',
    label: 'Sender display name',
    type: 'text',
    section: 'mailer',
  },
  {
    key: 'mailer.imap.enabled',
    valueFrom: 'mailer.imap.enabled',
    encrypted: false,
    default: false,
    label: 'Enable email import',
    type: 'checkbox',
    section: 'mailer',
  },
  {
    key: 'mailer.imap.host',
    valueFrom: 'mailer.imap.host',
    encrypted: false,
    default: '',
    label: 'IMAP server host',
    type: 'text',
    section: 'mailer',
  },
  {
    key: 'mailer.imap.port',
    valueFrom: 'mailer.imap.port',
    encrypted: false,
    default: '993',
    label: 'IMAP server port',
    type: 'text',
    required: true,
    pattern: '^[1-9][0-9]{0,4}$',
    patternMessage: 'Use the IMAP port number, usually 993 or 143.',
    section: 'mailer',
  },
  {
    key: 'mailer.imap.secure',
    valueFrom: 'mailer.imap.secure',
    encrypted: false,
    default: true,
    label: 'Use secure IMAP connection',
    type: 'checkbox',
    section: 'mailer',
  },
  {
    key: 'mailer.imap.username',
    valueFrom: 'mailer.imap.username',
    encrypted: false,
    default: '',
    label: 'IMAP username',
    type: 'text',
    section: 'mailer',
  },
  {
    key: 'mailer.imap.password',
    valueFrom: 'mailer.imap.password',
    encrypted: true,
    default: '',
    label: 'IMAP password',
    type: 'password',
    section: 'mailer',
  },
  {
    key: 'mailer.imap.mailbox',
    valueFrom: 'mailer.imap.mailbox',
    encrypted: false,
    default: 'INBOX',
    label: 'IMAP mailbox',
    type: 'text',
    required: true,
    section: 'mailer',
  },
  {
    key: 'mailer.imap.importOwnerUuid',
    valueFrom: 'mailer.imap.importOwnerUuid',
    encrypted: false,
    default: '',
    label: 'Email import owner UUID',
    type: 'text',
    section: 'mailer',
  },
  {
    key: 'mailer.imap.pollIntervalMs',
    valueFrom: 'mailer.imap.pollIntervalMs',
    encrypted: false,
    default: '60000',
    label: 'Email polling interval (ms)',
    type: 'text',
    required: true,
    pattern: '^[1-9][0-9]*$',
    patternMessage: 'Use a positive whole number of milliseconds.',
    section: 'mailer',
  },
  {
    key: 'mailer.imap.deleteAfterImport',
    valueFrom: 'mailer.imap.deleteAfterImport',
    encrypted: false,
    default: false,
    label: 'Delete messages after successful import',
    type: 'checkbox',
    section: 'mailer',
  },
  {
    key: 'calendar.enabled',
    valueFrom: 'calendar.enabled',
    encrypted: false,
    default: false,
    label: 'Enable calendar integration',
    type: 'checkbox',
    section: 'calendar',
  },
  {
    key: 'calendar.dueDateField',
    valueFrom: 'calendar.dueDateField',
    encrypted: false,
    default: 'dueDate',
    label: 'Due-date metadata key',
    type: 'metadata',
    required: true,
    section: 'calendar',
  },
  {
    key: 'backup.root',
    valueFrom: 'backup.root',
    encrypted: false,
    default: '/app/backup',
    label: 'Backup root path',
    type: 'text',
    required: true,
    section: 'maintenance',
  },
  {
    key: 'backup.enabled',
    valueFrom: 'backup.enabled',
    encrypted: false,
    default: false,
    label: 'Enable scheduled backups',
    type: 'checkbox',
    section: 'maintenance',
  },
  {
    key: 'backup.schedule',
    valueFrom: 'backup.schedule',
    encrypted: false,
    default: '0 2 * * *',
    label: 'Backup schedule (cron)',
    type: 'text',
    required: true,
    section: 'maintenance',
  },
  {
    key: 'backup.retentionDays',
    valueFrom: 'backup.retentionDays',
    encrypted: false,
    default: '30',
    label: 'Keep backups for (days)',
    type: 'text',
    required: true,
    section: 'maintenance',
  },
  {
    key: 'backup.encryptionPassword',
    valueFrom: 'backup.encryptionPassword',
    encrypted: true,
    default: '',
    label: 'Encrypted backup password',
    type: 'password',
    section: 'maintenance',
  },
  {
    key: 'backup.scope',
    valueFrom: 'backup.scope',
    encrypted: false,
    default: 'full',
    label: 'Backup contents',
    type: 'select',
    options: ['database', 'full'],
    section: 'maintenance',
  },
  {
    key: 'backup.provider',
    valueFrom: 'backup.provider',
    encrypted: false,
    default: 'none',
    label: 'External backup provider',
    type: 'select',
    options: ['none', 'dropbox'],
    section: 'maintenance',
  },
  {
    key: 'backup.remoteFolder',
    valueFrom: 'backup.remoteFolder',
    encrypted: false,
    default: '/Binder backups',
    label: 'External backup folder',
    type: 'text',
    required: true,
    section: 'maintenance',
  },
  {
    key: 'maintenance.timezone',
    valueFrom: 'maintenance.timezone',
    encrypted: false,
    default: 'UTC',
    label: 'Maintenance timezone',
    type: 'text',
    required: true,
    section: 'maintenance',
  },
  {
    key: 'maintenance.storageConsistency.enabled',
    valueFrom: 'maintenance.storageConsistency.enabled',
    encrypted: false,
    default: true,
    label: 'Enable document storage consistency checks',
    type: 'checkbox',
    section: 'maintenance',
  },
  {
    key: 'maintenance.storageConsistency.schedule',
    valueFrom: 'maintenance.storageConsistency.schedule',
    encrypted: false,
    default: '0 3 * * *',
    label: 'Storage consistency schedule (cron)',
    type: 'text',
    required: true,
    section: 'maintenance',
  },
  {
    key: 'security.malwareScan.required',
    valueFrom: 'security.malwareScan.required',
    encrypted: false,
    default: true,
    label: 'Require malware scanning before processing',
    type: 'checkbox',
    section: 'security',
  },
  {
    key: 'security.malwareScan.command',
    valueFrom: 'security.malwareScan.command',
    encrypted: false,
    default: 'clamdscan',
    label: 'Malware scanner executable',
    type: 'text',
    required: true,
    section: 'security',
  },
  {
    key: 'security.malwareScan.timeoutMs',
    valueFrom: 'security.malwareScan.timeoutMs',
    encrypted: false,
    default: '120000',
    label: 'Malware scan timeout (ms)',
    type: 'text',
    required: true,
    section: 'security',
  },
  {
    key: 'documents.storageRoot',
    valueFrom: 'documents.storageRoot',
    encrypted: false,
    default: '',
    label: 'Storage root (absolute or application base path)',
    type: 'text',
    required: false,
    section: 'documents',
  },
  {
    key: 'documents.maxUploadBytes',
    valueFrom: 'documents.maxUploadBytes',
    encrypted: false,
    default: '52428800',
    label: 'Maximum upload size (bytes)',
    type: 'text',
    required: true,
    section: 'documents',
  },
  {
    key: 'documents.reviewState.clearOn',
    valueFrom: 'documents.reviewState.clearOn',
    encrypted: false,
    default: 'metadata',
    label: 'Clear the new-document marker after',
    type: 'select',
    required: true,
    options: ['metadata', 'open'],
    section: 'documents',
  },
  {
    key: 'documents.pdfa.enabled',
    valueFrom: 'documents.pdfa.enabled',
    encrypted: false,
    default: false,
    label: 'Automatically create PDF/A-2b archive derivatives',
    type: 'checkbox',
    section: 'documents',
  },
  {
    key: 'pipeline.pollIntervalMs',
    valueFrom: 'pipeline.pollIntervalMs',
    encrypted: false,
    default: '2000',
    label: 'Worker polling interval (ms)',
    type: 'text',
    required: true,
    section: 'pipeline',
  },
  {
    key: 'pipeline.lockTimeoutMs',
    valueFrom: 'pipeline.lockTimeoutMs',
    encrypted: false,
    default: '900000',
    label: 'Worker lock timeout (ms)',
    type: 'text',
    required: true,
    section: 'pipeline',
  },
  {
    key: 'pipeline.reconcileIntervalMs',
    valueFrom: 'pipeline.reconcileIntervalMs',
    encrypted: false,
    default: '30000',
    label: 'Reconciliation interval (ms)',
    type: 'text',
    required: true,
    section: 'pipeline',
  },
  {
    key: 'inbox.enabled',
    valueFrom: 'inbox.enabled',
    encrypted: false,
    default: false,
    label: 'Enable inbox import',
    type: 'checkbox',
    section: 'documents',
  },
  {
    key: 'inbox.path',
    valueFrom: 'inbox.path',
    encrypted: false,
    default: 'inbox',
    label: 'Inbox path (absolute or relative to storage root)',
    type: 'text',
    required: true,
    section: 'documents',
  },
  {
    key: 'inbox.importOwnerUuid',
    valueFrom: 'inbox.importOwnerUuid',
    encrypted: false,
    default: '',
    label: 'Inbox import owner UUID',
    type: 'text',
    required: false,
    section: 'documents',
  },
  {
    key: 'inbox.pollIntervalMs',
    valueFrom: 'inbox.pollIntervalMs',
    encrypted: false,
    default: '5000',
    label: 'Inbox polling interval (ms)',
    type: 'text',
    required: true,
    section: 'documents',
  },
  {
    key: 'inbox.stabilityMs',
    valueFrom: 'inbox.stabilityMs',
    encrypted: false,
    default: '2000',
    label: 'Inbox file stability delay (ms)',
    type: 'text',
    required: true,
    section: 'documents',
  },
  {
    key: 'inbox.completionStage',
    valueFrom: 'inbox.completionStage',
    encrypted: false,
    default: 'ai-analysis',
    label: 'Remove inbox item after',
    type: 'select',
    required: true,
    options: ['import', 'ai-analysis'],
    section: 'documents',
  },
  {
    key: 'pipeline.ocrLanguages',
    valueFrom: 'pipeline.ocrLanguages',
    encrypted: false,
    default: 'deu+eng',
    label: 'OCR languages',
    type: 'text',
    required: true,
    section: 'pipeline',
  },
  {
    key: 'pipeline.ocrJobs',
    valueFrom: 'pipeline.ocrJobs',
    encrypted: false,
    default: '1',
    label: 'OCR parallel jobs',
    type: 'text',
    required: true,
    pattern: '^[1-9][0-9]*$',
    patternMessage: 'Use a positive number. One job is recommended for small servers.',
    section: 'pipeline',
  },
  {
    key: 'pipeline.ocrRotatePages',
    valueFrom: 'pipeline.ocrRotatePages',
    encrypted: false,
    default: true,
    label: 'Automatically rotate OCR pages',
    type: 'checkbox',
    section: 'pipeline',
  },
  {
    key: 'pipeline.ocrDeskew',
    valueFrom: 'pipeline.ocrDeskew',
    encrypted: false,
    default: false,
    label: 'Deskew OCR pages',
    type: 'checkbox',
    section: 'pipeline',
  },
  {
    key: 'embeddings.enabled',
    valueFrom: 'embeddings.enabled',
    encrypted: false,
    default: false,
    label: 'Automatically create semantic embeddings',
    type: 'checkbox',
    section: 'pipeline',
  },
  {
    key: 'embeddings.chunkSize',
    valueFrom: 'embeddings.chunkSize',
    encrypted: false,
    default: '1200',
    label: 'Embedding chunk size (characters)',
    type: 'text',
    required: true,
    section: 'pipeline',
  },
  {
    key: 'embeddings.chunkOverlap',
    valueFrom: 'embeddings.chunkOverlap',
    encrypted: false,
    default: '200',
    label: 'Embedding chunk overlap (characters)',
    type: 'text',
    required: true,
    section: 'pipeline',
  },
  {
    key: 'ai.titleSuggestions.enabled',
    valueFrom: 'ai.titleSuggestions.enabled',
    encrypted: false,
    default: false,
    label: 'Enable AI title suggestions',
    type: 'checkbox',
    section: 'ai',
  },
  {
    key: 'ai.automaticClassification.enabled',
    valueFrom: 'ai.automaticClassification.enabled',
    encrypted: false,
    default: false,
    label: 'Automatically apply high-confidence AI classification',
    type: 'checkbox',
    section: 'ai',
  },
  {
    key: 'ai.automaticAnalysis.enabled',
    valueFrom: 'ai.automaticAnalysis.enabled',
    encrypted: false,
    default: false,
    label: 'Automatically analyze imported documents with AI',
    type: 'checkbox',
    section: 'ai',
  },
  {
    key: 'ai.automaticClassification.confidence',
    valueFrom: 'ai.automaticClassification.confidence',
    encrypted: false,
    default: '0.8',
    label: 'Automatic classification confidence threshold (0–1)',
    type: 'text',
    required: true,
    pattern: '^(0(?:\\.\\d+)?|1(?:\\.0+)?)$',
    patternMessage: 'Use a value from 0 to 1. Example: 0.8 means 80%.',
    section: 'ai',
  },
  {
    key: 'ai.documentAnalysis.prompt',
    valueFrom: 'ai.documentAnalysis.prompt',
    encrypted: false,
    default:
      'Classify the document and create a concise human-readable title. Use only the supplied document types, categories, tags, and metadata keys. Never invent UUIDs, tags, types, categories, or custom keys. Use null or [] when uncertain. Return only the requested JSON object; never include markdown.',
    label: 'Document analysis prompt',
    type: 'textarea',
    required: true,
    section: 'ai',
  },
  {
    key: 'ai.fileAnalysis.expirationSeconds',
    valueFrom: 'ai.fileAnalysis.expirationSeconds',
    encrypted: false,
    default: '3600',
    label: 'Uploaded analysis file lifetime (seconds)',
    type: 'text',
    required: true,
    pattern: '^[0-9]+$',
    patternMessage: 'Use a whole number between 3600 and 2592000 seconds.',
    section: 'ai',
  },
  {
    key: 'ai.fileAnalysis.timeoutMs',
    valueFrom: 'ai.fileAnalysis.timeoutMs',
    encrypted: false,
    default: '120000',
    label: 'PDF analysis request timeout (ms)',
    type: 'text',
    required: true,
    pattern: '^[0-9]+$',
    patternMessage: 'Use a positive whole number of milliseconds.',
    section: 'ai',
  },
  {
    key: 'oidc.ISSUER_URL',
    valueFrom: 'OIDC_ISSUER_URL',
    encrypted: false,
    default: '',
    label: 'Issuer',
    type: 'text',
    required: true,
    section: 'oidc',
  },
  {
    key: 'oidc.CLIENT_ID',
    valueFrom: 'OIDC_CLIENT_ID',
    encrypted: false,
    default: '',
    label: 'Client ID',
    type: 'text',
    required: true,
    section: 'oidc',
  },
  {
    key: 'oidc.CLIENT_SECRET',
    valueFrom: 'OIDC_CLIENT_SECRET',
    encrypted: true,
    default: '',
    label: 'Client Secret',
    type: 'password',
    required: true,
    section: 'oidc',
  },
  {
    key: 'oidc.email_verified',
    valueFrom: 'email_verified',
    encrypted: false,
    default: false,
    label: 'Only accept verified eMails',
    type: 'checkbox',
    section: 'oidc',
  },
  {
    key: 'oidc.ACR_VALUES',
    valueFrom: 'acrValues',
    encrypted: false,
    default: '',
    label: 'Pass ACR Values if needed',
    type: 'text',
    section: 'oidc',
  },
];
