import { SettingsMapItem, SettingsSection } from "./settings";

export const settingsSections: SettingsSection[] = [
  {
    key: 'common',
    label: 'Common Settings',
  },
  {
    key: 'mailer',
    label: 'Mailer Settings',
  },
  {
    key: 'oidc',
    label: 'SSO/OIDC Login',
  },
  {
    key: 'documents',
    label: 'Document storage',
  },
  {
    key: 'pipeline',
    label: 'Processing pipeline',
  },
];

export const settingsMap: SettingsMapItem[] = [
  {
    key: 'documents.storageRoot',
    valueFrom: 'documents.storageRoot',
    encrypted: false,
    default: '',
    label: 'Storage root',
    type: 'text',
    required: false,
    section: 'documents',
  },
  {
    key: 'documents.maxUploadBytes',
    valueFrom: 'documents.maxUploadBytes',
    encrypted: false,
    default: '52428800',
    label: 'Maximum upload size (bytes)',
    type: 'text',
    required: true,
    section: 'documents',
  },
  {
    key: 'pipeline.pollIntervalMs',
    valueFrom: 'pipeline.pollIntervalMs',
    encrypted: false,
    default: '2000',
    label: 'Worker polling interval (ms)',
    type: 'text',
    required: true,
    section: 'pipeline',
  },
  {
    key: 'pipeline.lockTimeoutMs',
    valueFrom: 'pipeline.lockTimeoutMs',
    encrypted: false,
    default: '900000',
    label: 'Worker lock timeout (ms)',
    type: 'text',
    required: true,
    section: 'pipeline',
  },
  {
    key: 'pipeline.reconcileIntervalMs',
    valueFrom: 'pipeline.reconcileIntervalMs',
    encrypted: false,
    default: '30000',
    label: 'Reconciliation interval (ms)',
    type: 'text',
    required: true,
    section: 'pipeline',
  },
  {
    key: 'pipeline.ocrLanguages',
    valueFrom: 'pipeline.ocrLanguages',
    encrypted: false,
    default: 'deu+eng',
    label: 'OCR languages',
    type: 'text',
    required: true,
    section: 'pipeline',
  },
  {
    key: 'embeddings.enabled', valueFrom: 'embeddings.enabled', encrypted: false, default: false,
    label: 'Enable hosted semantic embeddings', type: 'checkbox', section: 'pipeline',
  },
  {
    key: 'embeddings.provider', valueFrom: 'embeddings.provider', encrypted: false, default: 'openai-compatible',
    label: 'Embedding provider', type: 'text', required: true, section: 'pipeline',
  },
  {
    key: 'embeddings.endpoint', valueFrom: 'embeddings.endpoint', encrypted: false,
    default: 'https://api.openai.com/v1/embeddings', label: 'Embedding endpoint', type: 'text', required: true, section: 'pipeline',
  },
  {
    key: 'embeddings.model', valueFrom: 'embeddings.model', encrypted: false, default: 'text-embedding-3-small',
    label: 'Embedding model', type: 'text', required: true, section: 'pipeline',
  },
  {
    key: 'embeddings.apiKey', valueFrom: 'embeddings.apiKey', encrypted: true, default: '',
    label: 'Embedding API key', type: 'password', required: false, section: 'pipeline',
  },
  {
    key: 'embeddings.chunkSize', valueFrom: 'embeddings.chunkSize', encrypted: false, default: '1200',
    label: 'Embedding chunk size (characters)', type: 'text', required: true, section: 'pipeline',
  },
  {
    key: 'embeddings.chunkOverlap', valueFrom: 'embeddings.chunkOverlap', encrypted: false, default: '200',
    label: 'Embedding chunk overlap (characters)', type: 'text', required: true, section: 'pipeline',
  },
    {
    key: 'oidc.ISSUER_URL',
    valueFrom: 'OIDC_ISSUER_URL',
    encrypted: false,
    default: '',
    label: 'Issuer',
    type: 'text',
    required: true,
    section: 'oidc',
  },
  {
    key: 'oidc.CLIENT_ID',
    valueFrom: 'OIDC_CLIENT_ID',
    encrypted: false,
    default: '',
    label: 'Client ID',
    type: 'text',
    required: true,
    section: 'oidc',
  },
  {
    key: 'oidc.CLIENT_SECRET',
    valueFrom: 'OIDC_CLIENT_SECRET',
    encrypted: true,
    default: '',
    label: 'Client Secret',
    type: 'password',
    required: true,
    section: 'oidc',
  },
  {
    key: 'oidc.email_verified',
    valueFrom: 'email_verified',
    encrypted: false,
    default: false,
    label: 'Only accept verified eMails',
    type: 'checkbox',
    section: 'oidc',
  },
  {
    key: 'oidc.ACR_VALUES',
    valueFrom: 'acrValues',
    encrypted: false,
    default: '',
    label: 'Pass ACR Values if needed',
    type: 'text',
    section: 'oidc',
  }
]
